User Modal
HackGT/match pull request #13
Opened 2023-07-27 08:38 UTC by amtang325

added a user modal pop-up for when a user card is clicked

2023-07-27 15:51 UTC, Roshan-D requested changes
It looks a little funky for me with the descriptions being of variable length, could you fix the css so the button is just stuck to the bottom of each card

<img width="1014" alt="Screenshot 2023-07-27 at 8 49 55 AM" src="https://github.com/HackGT/match/assets/38771624/da297f23-0bcf-4d56-ad96-4730e380483e">

2023-07-27 21:46 UTC, thaneesh-babu requested changes
Good start! Like said above, there are some styling changes that need to be made:
- The 'see profile' option should be inside the card
- The UserModal should be bigger in size. Although we will be implementing word limit for the description, users would be allowed to write quite a bit and the current space isn't enough for that. Update descriptions of some users to have longer descriptions upto 200 characters

2023-07-27 21:46 UTC, thaneesh-babu commented on src/components/UserModal.tsx
> +              </Button> */}
remove this

2023-07-31 00:14 UTC, thaneesh-babu approved these changes
lgtm!

2023-07-31 00:14 UTC, merged